name: Cypress CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    container:
      image: cypress/browsers:node-22.19.0-chrome-139.0.7258.154-1-ff-142.0.1-edge-139.0.3405.125-1

    steps:
      # 1 Repository auschecken
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2 Abhängigkeiten installieren
      - name: Install dependencies
        run: npm ci

      # 3 Demo-App starten und Cypress Tests ausführen      
      #- name: Run Cypress
      #  run: npx start-server-and-test "npm start" http://localhost:3000 "npx cypress run --browser chrome --headless"
      
      - name: Start App
        run: |
          npm start &
          npx wait-on http://localhost:3000

      - name: Run Cypress Tests
        run: npx cypress run --browser chrome --headless

      # 4 Artefakte hochladen
      - name: Upload Cypress artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-artifacts
          path: |
            results
            cypress/videos
            cypress/screenshots